SELECT C.CAR_ID, C.CAR_TYPE, ROUND((C.DAILY_FEE * (1-D.DISCOUNT_RATE/100) * 30),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE='30일 이상'
WHERE C.CAR_TYPE IN ('세단','SUV') 
        AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
        AND ROUND((C.DAILY_FEE * (1-D.DISCOUNT_RATE/100) * 30),0) >= 500000 
        AND ROUND((C.DAILY_FEE * (1-D.DISCOUNT_RATE/100) * 30),0) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;