-- 한 개발자가 Python과 C# 둘 다 가지고 있으면, 두 번 조회되므로 DISTINCT로 중복제거
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME 
FROM DEVELOPERS D JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE = S.CODE
WHERE S.NAME IN ('C#','Python')
ORDER BY D.ID ASC;