SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
        (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA
         WHERE YEAR(DIFFERENTIATION_DATE)=YEAR(E.DIFFERENTIATION_DATE))-SIZE_OF_COLONY AS YEAR_DEV,
        ID
FROM ECOLI_DATA E
ORDER BY YEAR ASC, YEAR_DEV ASC;