SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN 
        (SELECT CATEGORY, MAX(PRICE) FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('과자','국','김치','식용유')
        GROUP BY CATEGORY)
ORDER BY PRICE DESC;
-- CATEGORY와 PRICE를 함께 비교하기